### ISSUE TITLE
How do I get it working?

### ISSUE THREAD

**Issue by felippenardi** [0x0dea/vim-molasses#1]
Hello,

I installed the plugin, but I don't understand how to check if it is working or not. Pressing "h, j, k or l" repeatedly works just as before. The Readme is missing information on what should be expected to happen.

**Comment by 0x0dea** [comment]
Hey, Felippe.

If you have correctly installed the plugin, you should find that you are unable to, for instance, hold down your `j` key in order to "quickly" move downward. If you are not in the habit of doing this, you don't need this plugin's assistance in breaking it.

**Comment by felippenardi** [comment]
I think I didn't installed it correctly, I'll try again! Thanks @0x0dea
