### ISSUE TITLE
Occasionally hjkl are completely disabled

### ISSUE THREAD

**Issue by jefflund** [0x0dea/vim-molasses#2]
Occasionally the punished keys become completely non-functional. Everything else works correctly so I can still change modes, and use other movements, but moving a single line or character because a no op.

**Comment by 0x0dea** [comment]
Hi, Jeff.

I'm unable to reproduce this issue, but that the plugin initially works before failing would seem to point the finger at the only "dynamic" portion of the script, namely the `reltime()` function. Vim's documentation mentions that its return value varies by system, making its being the culprit quite likely. Would you mind telling me precisely which version of Fedora you're running?

**Comment by jefflund** [comment]
I actually observed this behavior on Goobuntu... For all intents and purposes this is just Ubuntu 14.04, albeit with some Google-specific stuff added on.

**Comment by jefflund** [comment]
So I observed this behavior just starting yesterday when I enabled this plugin, so I assumed it was the cause. However, it is just happened even after I disabled it. Happily, I think that means vim-molasses is off the hook! Apologies for the false report.
