### ISSUE TITLE
How to define arrow keys as molasses_key

### ISSUE THREAD

**Issue by statox** [0x0dea/vim-molasses#3]
I can't define the arrow key as molasses_key. I tried something like than in .vimrc 
`let g:molasses_keys = ["<Up>",'h','j','k','l']` 
but it doesn't seems to work.

How should I do it?

(This plugin is really cool!)

**Comment by 0x0dea** [comment]
Hey, Adrien. I'm glad you like the plugin!

Your declaration of `g:molasses_keys` was correct, but Vim does something rather strange with strings containing special keys when they're passed to functions. Thank you for bringing this anomaly to my attention, and please let me know if this update allows you to punish arrow keys.

**Comment by statox** [comment]
Hey, 

Thanks for your quick answer. The last commit make it work but each time i open vim, the first time I use a special key I have the following error:
![molasses_error](https://cloud.githubusercontent.com/assets/6271599/6977353/d29fe6bc-d9bb-11e4-8371-a7f480a20493.png)

In English it says:
`Error detected while treating function <SNR>53_Molasses :`
`Line 5 :` 
`E716: The key <80>ku doesn't exists in the Dictionnary.`

After that the plugin seems to work properly.

**Comment by 0x0dea** [comment]
I'm unable to reproduce that error (using `let g:molasses_keys = ["<Up>"]`), and it's very strange that it should occur. The first time you press a punished key, its key code is indeed not present in the dictionary, but this is (or at least should be) explicitly handled by immediately adding it to the dictionary and returning the pressed key. I can't imagine what might prevent this sequence of events from executing as intended, but I'll let you know if I'm able to trigger and subsequently fix this regrettable bug.

**Comment by statox** [comment]
Indeed that seems pretty strange but sadly I don't know how to help you to fix it.

Don't hesitate to contact me again if I can provide you more info on my installation or some help to testing your plugin.
